const bgbahaya = document.getElementsByClassName("bgbahaya");
for (let i = 0; i < bgbahaya.length; i++) {
  bgbahaya[i].innerHTML = "<h1 class='keterangan-font-size'>Situs ini <span class='color-red'>berbahaya</span> menurut kami berdasarkan laporan dari admin kami yang telah mencoba di situs ini, situs ini dapat menyebabkan <span class='color-red'>ketidak nyamanan untuk pemain</span> berikut penyebab ketidak nyamanan  ?<br/>1. Tidak membayar kemenangan besar member<br/>2. withdraw tidak di proses<br/>3. password id member di ubah tanpa persetujuan pemilik id<br/>4. Hak-hak member tidak di berikan<br/>5. Mempersulit member dengan berbagai alasan<br/>6. id anda dapat di masuki oleh admin tanpa persetujuan anda terlebih dahulu dan saldo di mainkan sampai habis, biasanya jika ini terjadi pada id anda ciri-cirinya anda tidak akan bisa login dengan password yang terakhir anda gunakan sebab sudah di ubah admin untuk bisa masuk ke dalam id anda<br/><br/>Semua situs yang kami tandai <span class='color-red'>merah</span> pernah melakukan salah satu hal di atas sebab itu kami beri tanda warna <span class='color-red'>MERAH</span> yang berarti <span class='color-red'>BERBAHAYA</span> kami tekankan kembali keputusan mutlak ada pada diri anda sendiri tidak ada paksaan apapun dari kami untuk anda mepercayai informasi dari kami ini bisa saja hal yang kami alami tidak terjadi kepada anda namun kami tidak akan mengupdate link alternatif tanpa vpn terbaru situs yang kami tandai merah ini namun anda tetap bisa berkomunikasi dengan situs tersebut dengan menekan <span class='color-red'>TOMBOL TETAP MASUK</span><br/><br/>Kami rekomendasikan situs yang di beri warna <span class='color-green'>HIJAU</span> oleh kami yang berarti <span class='color-green'>AMAN</span> karena belum pernah ada keanehan selama kami mencoba situs tersebut<br/></h1>";
}

const bgwaspada = document.getElementsByClassName("bgwaspada");
for (let i = 0; i < bgwaspada.length; i++) {
  bgwaspada[i].innerHTML = "<h1 class='keterangan-font-size'>Situs ini belum di coba oleh admin kami apabila anda ingin mencoba bermain di situs ini anda <span class='color-red'>PERLU WASPADA</span> karena bisa saja situs ini tidak aman dan sementara untuk link alternatif tanpa vpn situs ini tidak akan di update oleh kami namun anda tetap bisa berkomunikasi dengan admin situs tersebut dengan menekan tombol <span class='color-red'>TETAP MASUK</span><br/><br/>kami merekomendasikan situs yang kami beri tanda <span class='color-green'>berwarna HIJAU yang berarti AMAN</span> dan sudah di uji coba admin kami</h1>";
}

const bgdomain = document.getElementsByClassName("bgdomain");
for (let i = 0; i < bgdomain.length; i++) {
  bgdomain[i].innerHTML = "<h1 class='keterangan-font-size'>Semua situs yang tersedia di ruang ini tidak seluruhnya kami update link alternatif terbaru tanpa vpn, hanya situs yang benar-benar aman menurut kami yang akan kami update setiap hari jangan lupa untuk menekan tombol UPDATE terlebih dahulu agar seluruh link terbaru yang sudah di update otomatis dapat di pergunakan dan untuk tombol UPDATE berada di sudut kiri atas pada layar anda<br/><br/>Situs berstatus <span class='color-green'>AMAN BERWARNA HIJAU</span> Link alternatif terbaru akan otomatis update paling cepat 5 menit dan paling lambat 12 jam setelah link sebelumnya terkena gangguan akses<br/><br/>Situs berstatus <span class='color-yellow'>WASPADA BERWARNA KUNING</span> dan Situs berstatus <span class='color-red'>BAHAYA BERWARNA MERAH</span> link tidak kami cantumkan karena menurut kami situs tersebut tidak aman untuk di mainkan namun kami tetap menghargai keinginan anda sebagai member situs tersebut anda tetap bisa berkomunikasi langsung kepada situsnya dengan menekan tombol TETAP MASUK yang telah kami sediakan dan link alternatif boleh anda minta langsung kepada admin situs tersebut</h1>";
}

const bgchatadmin = document.getElementsByClassName("bgchatadmin");
for (let i = 0; i < bgchatadmin.length; i++) {
  bgchatadmin[i].innerHTML = "<h1 class='keterangan-font-size'>Tombol CHAT ini di sediakan untuk berkomunikasi dengan admin</br></br>Jika ingin mengirmkan pesan untuk admin tanpa perlu jawaban gunakan chat <span class='color-green'>TAWK</span></br>Contoh 1 </br>tambahkan situs Lotto01 ke dalam</br>Contoh 2</br>min tambahin situs Kenzo188</br>Contoh 3</br>min link Lotto01 tidak bisa buka tolong update</br>intinya sampaikan seluruh hal yang ingin anda sampaikan dalam chat <span class='color-green'>TAWK</span> ini, nanti akan di baca oleh admin dan di kerjakan tanpa membalas pesan anda</br></br>Jika ingin mengirmkan pesan yang akan di balas oleh admin maka gunakan <span class='color-blue'>FACEBOOK</span> untuk menghubungi admin</h1>";
}
