const bgbahaya = document.getElementsByClassName("bgbahaya");
for (let i = 0; i < bgbahaya.length; i++) {
  bgbahaya[i].innerHTML = "<h1 class='keterangan-font-size'>Mohon maaf setelah di coba kami putuskan tidak mempercayai situs ini sebab itu link terbaru tanpa menggunakan vpn tidak kami sediakan lagi di ruang kami ini sebagai gantinya kami sediakan sarana komunikasi ke situs resminya langsung di tombol <span class='color-red'>TETAP MASUK</span>, agar anda tetap bisa berkomunikasi dengan situs ini secara langsung, hanya upaya ini yang dapat kami lakukan untuk menghargai teman-teman yang telah melakukan request dari tombol chat di atas untuk menambahkan situs tersebut kedalam ruang kami ini, alasan situs tersebut tidak dapat di percaya oleh kami tidak akan kami sebar luaskan sebab belum tentu apa yang terjadi kepada kami akan berlaku kepada anda dan kami doakan yang terbaik untuk anda semoga tetap aman bermain di situs tersebut<br/><br/>Kami hanya merekomendasikan situs yang benar-benar <span class='color-green'>AMAN</span> dan dapat di percaya pastinya membayar seluruh kemenangan dan memberikan hak pemain secara penuh tidak kurang maupun lebih maka situs tersebut akan kami beri warna <span class='color-green'>HIJAU</span> yang berarti <span class='color-green'>AMAN</span> dan belum pernah melakukan hal yang dapat merusak kenyamanan pemain<br/>Berikut kriteria situs yang benar-benar <span class='color-green'>aman</span><br/>1. Tidak mengambil hak member seperti bonus maupun komisi<br/>2. Tidak mempersulit segala permasalahan id member<br/>3. Withdraw berapapun tetap di bayar baik besar maupun kecil<br/>4. Tidak melakukan lock id pemain yang menang besar<br/>5. Tidak membajak id pemain dan memainkan saldonya sampai habis, biasanya jika ini terjadi ciri-cirinya anda tidak akan bisa melakukan login dengan password yang terakhir anda gunakan sebab sudah di ubah oleh admin situs tersebut untuk dapat melakukan login ke dalam id anda dan bermain hal ini sangat berbahaya sebab jika anda menuduh admin maka mereka akan membalikkan fakta bahwa anda sendiri yang memainkan sampai habis berdasarkan adanya history bermain yang padahal pelaku adalah mereka sendiri<br/>Semua situs yang kami beritanda <span class='color-green'>AMAN</span> tidak pernah melakukan salah satu hal di atas</h1>";
}

const bgwaspada = document.getElementsByClassName("bgwaspada");
for (let i = 0; i < bgwaspada.length; i++) {
  bgwaspada[i].innerHTML = "<h1 class='keterangan-font-size'>Situs ini belum di coba oleh admin kami apabila anda ingin mencoba bermain di situs ini anda <span class='color-red'>PERLU WASPADA</span> karena bisa saja situs ini tidak aman dan sementara untuk link alternatif tanpa vpn situs ini tidak akan di update oleh kami namun anda tetap bisa berkomunikasi dengan admin situs tersebut dengan menekan tombol <span class='color-red'>TETAP MASUK</span><br/><br/>kami merekomendasikan situs yang kami beri tanda <span class='color-green'>berwarna HIJAU yang berarti AMAN</span> dan sudah di uji coba admin kami</h1>";
}

const bgdomain = document.getElementsByClassName("bgdomain");
for (let i = 0; i < bgdomain.length; i++) {
  bgdomain[i].innerHTML = "<h1 class='keterangan-font-size'>Semua situs yang tersedia di ruang ini tidak seluruhnya kami update link alternatif terbaru tanpa vpn, hanya situs yang benar-benar aman menurut kami yang akan kami update setiap hari jangan lupa untuk menekan tombol UPDATE terlebih dahulu agar seluruh link terbaru yang sudah di update otomatis dapat di pergunakan dan untuk tombol UPDATE berada di sudut kiri atas pada layar anda<br/><br/>Situs berstatus <span class='color-green'>AMAN BERWARNA HIJAU</span> Link alternatif terbaru akan otomatis update paling cepat 5 menit dan paling lambat 12 jam setelah link sebelumnya terkena gangguan akses<br/><br/>Situs berstatus <span class='color-yellow'>WASPADA BERWARNA KUNING</span> dan Situs berstatus <span class='color-red'>BAHAYA BERWARNA MERAH</span> link tidak kami cantumkan karena menurut kami situs tersebut tidak aman untuk di mainkan namun kami tetap menghargai keinginan anda sebagai member situs tersebut anda tetap bisa berkomunikasi langsung kepada situsnya dengan menekan tombol TETAP MASUK yang telah kami sediakan dan link alternatif boleh anda minta langsung kepada admin situs tersebut</h1>";
}

const bgchatadmin = document.getElementsByClassName("bgchatadmin");
for (let i = 0; i < bgchatadmin.length; i++) {
  bgchatadmin[i].innerHTML = "<h1 class='keterangan-font-size'>Tombol CHAT ini di sediakan untuk berkomunikasi dengan admin</br></br>Jika ingin mengirmkan pesan untuk admin tanpa perlu jawaban gunakan chat <span class='color-green'>TAWK</span></br>Contoh 1 </br>tambahkan situs Lotto01 ke dalam</br>Contoh 2</br>min tambahin situs Kenzo188</br>Contoh 3</br>min link Lotto01 tidak bisa buka tolong update</br>intinya sampaikan seluruh hal yang ingin anda sampaikan dalam chat <span class='color-green'>TAWK</span> ini, nanti akan di baca oleh admin dan di kerjakan tanpa membalas pesan anda</br></br>Jika ingin mengirmkan pesan yang akan di balas oleh admin maka gunakan <span class='color-blue'>FACEBOOK</span> untuk menghubungi admin</h1>";
}
